projects:
  remote:
    schemaPath: ./remote.schema.graphql
    extensions:
      endpoints:
        default:
          url: https://graphql.myshopify.com/api/graphql
          headers:
            x-shopify-storefront-access-token: 078bc5caa0ddebfa89cccb4a1baa1f5c
  rcp:
    schemaPath: ./schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000