projects:
  pokemon:
    schemaPath: ./pokemon.schema.graphql
    extensions:
      endpoints:
        default: http://localhost:9000
  rcp:
    schemaPath: ./schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000