projects:
  pokemon:
    schemaPath: ./pokemon.schema.graphql
    extensions:
      endpoints:
        default: https://api.graph.cool/relay/v1/Peerex
  rcp:
    schemaPath: ./schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000